/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Course.View;

import Admin.View.AdminMainPage;
import Course.Control.CourseController;
import Course.Model.Course;
import Course.Model.Program;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author haidt
 */
public class AddCourseForm extends javax.swing.JFrame {
    List<Course> listCourse;
    List<Program> listProgram;
    AdminMainPage adminMainPage;
    /**
     * Creates new form AddCourseForm
     * @param adminMainPage
     */
    public AddCourseForm(AdminMainPage adminMainPage) {
        this.adminMainPage=adminMainPage;
        initComponents();
        initialization();
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }
    private void initialization(){
        CourseController courseController= new CourseController();
        listCourse=courseController.getAllCourse();
        listProgram= courseController.getAllProgram();
        for(Program p: listProgram){
            jComboBoxProgram.addItem(p.getProgramId());
        }
        for(Course c: listCourse){
            jComboBoxCourseCondition.addItem(c.getCourseName());
        }
        jComboBoxCourseType.addItem("LT+BT,TH");
        jComboBoxCourseType.addItem("LT+BT");
        jSpinnerCredit.setValue(1);
        jTextFieldCourseId.setText(jComboBoxProgram.getSelectedItem().toString());
        jTextFieldCourseCondition.setText("");
        jTextFieldCourseCondition.setEditable(false);
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCourseId = new javax.swing.JLabel();
        jTextFieldCourseId = new javax.swing.JTextField();
        jLabelCourseName = new javax.swing.JLabel();
        jTextFieldCourseName = new javax.swing.JTextField();
        jLabelCredit = new javax.swing.JLabel();
        jSpinnerCredit = new javax.swing.JSpinner();
        jLabelCourseCondition = new javax.swing.JLabel();
        jComboBoxCourseCondition = new javax.swing.JComboBox<>();
        jLabelCourseType = new javax.swing.JLabel();
        jComboBoxCourseType = new javax.swing.JComboBox<>();
        jLabelProgram = new javax.swing.JLabel();
        jComboBoxProgram = new javax.swing.JComboBox<>();
        jButtonAddCourse = new javax.swing.JButton();
        jTextFieldCourseCondition = new javax.swing.JTextField();
        jButtonReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabelCourseId.setText("ID học phần");

        jLabelCourseName.setText("Tên học phần");

        jLabelCredit.setText("Số tín chỉ");

        jLabelCourseCondition.setText("Học phần điền kiện");

        jComboBoxCourseCondition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCourseConditionActionPerformed(evt);
            }
        });

        jLabelCourseType.setText("Loại học phần");

        jLabelProgram.setText("Chương trình");

        jButtonAddCourse.setText("Thêm học phần");
        jButtonAddCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddCourseMouseClicked(evt);
            }
        });

        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCourseType, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinnerCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(200, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelCourseId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jTextFieldCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBoxProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldCourseId, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCourseCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonReset))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jButtonAddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldCourseCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBoxCourseCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBoxCourseType, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCourseId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCourseId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCourseName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCourseCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCourseCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldCourseCondition)
                    .addComponent(jButtonReset, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCourseType, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCourseType, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.adminMainPage.setEnabled(true);
        this.adminMainPage.initialization();
    }//GEN-LAST:event_formWindowClosing

    private void jButtonAddCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddCourseMouseClicked
        // TODO add your handling code here:
        String programId= jComboBoxProgram.getSelectedItem().toString();
        String courseId= jTextFieldCourseId.getText();
        String courseName= jTextFieldCourseName.getText();
        int credit= Integer.parseInt(jSpinnerCredit.getValue().toString());
        String courseCondition= jTextFieldCourseCondition.getText();
        String courseType= jComboBoxCourseType.getSelectedItem().toString();
        Course course= new Course(courseId, courseName, credit, courseType, courseCondition, programId);
        CourseController courseController= new CourseController();
        switch(courseController.checkCourseValid(course)){
            case 0:{
                switch(courseController.addNewCourse(course)){
                    case 0:{
                        JOptionPane.showMessageDialog(this,"Thêm học phần thất bại kiểm tra kết nối mạng");
                        break;
                    }
                    case 1:{
                        JOptionPane.showMessageDialog(this,"Thêm học phần thành công");
                        break;
                    }
                }
            }
            case 1:{
                JOptionPane.showMessageDialog(this,"Định dạng ID học phần sai, ví dụ mẫu:IT1342");
                        break;
            }
            case 2:{
                JOptionPane.showMessageDialog(this,"Tên học phần thiếu");
                        break;
            }
            case 3:{
                JOptionPane.showMessageDialog(this,"Tín chỉ nhỏ hơn hoặc bằng 0");
                        break;
            }
            case 4:{
                JOptionPane.showMessageDialog(this,"Học phần tồn tại");
                        break;
            }
            case 5:{
                JOptionPane.showMessageDialog(this,"Kiểm tra kết nối mạng");
                        break;
            }
        }       
    }//GEN-LAST:event_jButtonAddCourseMouseClicked

    private void jComboBoxCourseConditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCourseConditionActionPerformed
        // TODO add your handling code here:
        String previousText= jTextFieldCourseCondition.getText();
        CourseController courseController= new CourseController();
        Course course= courseController.getCourseByCourseName(jComboBoxCourseCondition.getSelectedItem().toString());
        if(previousText.isEmpty()){           
            jTextFieldCourseCondition.setText(course.getCourseID());
        }
        else
            jTextFieldCourseCondition.setText(jTextFieldCourseCondition.getText()+"-"+course.getCourseID());
    }//GEN-LAST:event_jComboBoxCourseConditionActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        jTextFieldCourseCondition.setText("");
    }//GEN-LAST:event_jButtonResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddCourse;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JComboBox<String> jComboBoxCourseCondition;
    private javax.swing.JComboBox<String> jComboBoxCourseType;
    private javax.swing.JComboBox<String> jComboBoxProgram;
    private javax.swing.JLabel jLabelCourseCondition;
    private javax.swing.JLabel jLabelCourseId;
    private javax.swing.JLabel jLabelCourseName;
    private javax.swing.JLabel jLabelCourseType;
    private javax.swing.JLabel jLabelCredit;
    private javax.swing.JLabel jLabelProgram;
    private javax.swing.JSpinner jSpinnerCredit;
    private javax.swing.JTextField jTextFieldCourseCondition;
    private javax.swing.JTextField jTextFieldCourseId;
    private javax.swing.JTextField jTextFieldCourseName;
    // End of variables declaration//GEN-END:variables
}
