/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Course.View;

import Admin.View.AdminMainPage;
import Course.Control.CourseController;
import Course.Model.Course;
import CustomView.ObjectTableModel;
import CustomView.PaginatedTableDecorator;
import CustomView.PaginationDataProvider;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.TableModel;

/**
 *
 * @author haidt
 */
public class ManagementCourseForm extends javax.swing.JPanel {
    JTable tableCourse;
    AdminMainPage AdminPage;
    JPanel jPaneTable;
    TableModel tableModel;
    List<Course> listTableCourse= new ArrayList<>();
    /**
     * Creates new form ManagementCourseForm
     * @param AdminPage
     */
    public ManagementCourseForm(AdminMainPage AdminPage) {
        this.tableModel=createObjectDataModel();
        this.AdminPage=AdminPage;
        initComponents();
        initialization();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSearch = new javax.swing.JLabel();
        jLabelCourseId = new javax.swing.JLabel();
        jLabelCourseName = new javax.swing.JLabel();
        jTextFieldCourseId = new javax.swing.JTextField();
        jTextFieldCourseName = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jButtonEditCourse = new javax.swing.JButton();
        jButtonDeleteClass = new javax.swing.JButton();
        jScrollPaneTableCourse = new javax.swing.JScrollPane();
        jPanelTableCourse = new javax.swing.JPanel();
        jButtonAddCourse = new javax.swing.JButton();
        jButtonShowAllCourse = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(null);

        jLabelSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelSearch.setText("Tìm kiếm học phần: ");
        add(jLabelSearch);
        jLabelSearch.setBounds(10, 10, 150, 40);

        jLabelCourseId.setText("Mã học phần");
        add(jLabelCourseId);
        jLabelCourseId.setBounds(170, 10, 91, 45);

        jLabelCourseName.setText("Tên học phần");
        add(jLabelCourseName);
        jLabelCourseName.setBounds(170, 70, 91, 43);
        add(jTextFieldCourseId);
        jTextFieldCourseId.setBounds(270, 10, 416, 43);
        add(jTextFieldCourseName);
        jTextFieldCourseName.setBounds(270, 70, 418, 43);

        jButtonSearch.setText("Tìm kiếm");
        jButtonSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSearchMouseClicked(evt);
            }
        });
        add(jButtonSearch);
        jButtonSearch.setBounds(110, 135, 91, 35);

        jButtonEditCourse.setText("Sửa học phần");
        add(jButtonEditCourse);
        jButtonEditCourse.setBounds(258, 176, 137, 34);

        jButtonDeleteClass.setText("Xoá học phần");
        add(jButtonDeleteClass);
        jButtonDeleteClass.setBounds(401, 176, 138, 34);

        jPanelTableCourse.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelTableCourseLayout = new javax.swing.GroupLayout(jPanelTableCourse);
        jPanelTableCourse.setLayout(jPanelTableCourseLayout);
        jPanelTableCourseLayout.setHorizontalGroup(
            jPanelTableCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 818, Short.MAX_VALUE)
        );
        jPanelTableCourseLayout.setVerticalGroup(
            jPanelTableCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        jScrollPaneTableCourse.setViewportView(jPanelTableCourse);

        add(jScrollPaneTableCourse);
        jScrollPaneTableCourse.setBounds(10, 220, 820, 370);

        jButtonAddCourse.setText("Thêm học phần");
        jButtonAddCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddCourseMouseClicked(evt);
            }
        });
        add(jButtonAddCourse);
        jButtonAddCourse.setBounds(110, 180, 130, 30);

        jButtonShowAllCourse.setText("Hiện thị tất cả");
        jButtonShowAllCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonShowAllCourseMouseClicked(evt);
            }
        });
        add(jButtonShowAllCourse);
        jButtonShowAllCourse.setBounds(580, 140, 110, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSearchMouseClicked
        // TODO add your handling code here:
        String courseId= jTextFieldCourseId.getText();
        String courseName= jTextFieldCourseName.getText();
        
        if(courseId!=null||courseName!=null){
           CourseController controller= new CourseController();
           List<Course> listSearchCourse=controller.searchCourseByCourseNameOrCourseId(courseId, courseName);
           if(listSearchCourse==null||listSearchCourse.isEmpty()){
               JOptionPane.showMessageDialog(this,"Không tìm thấy học phần");
           }
           else{
                listTableCourse=listSearchCourse;
                updateTableCourse();
           }
        }
        else{
            JOptionPane.showMessageDialog(this,"Bạn chưa nhập thông tin tìm kiếm");
        }
    }//GEN-LAST:event_jButtonSearchMouseClicked

    private void jButtonShowAllCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonShowAllCourseMouseClicked
        // TODO add your handling code here:
        initialization();
    }//GEN-LAST:event_jButtonShowAllCourseMouseClicked

    private void jButtonAddCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddCourseMouseClicked
        // TODO add your handling code here:
        AddCourseForm addCourseForm= new AddCourseForm(AdminPage);
        addCourseForm.setVisible(true);
        AdminPage.setEnabled(false);
        
    }//GEN-LAST:event_jButtonAddCourseMouseClicked
    public void initialization(){ 
        CourseController courseController= new CourseController();
        listTableCourse= courseController.getAllCourse();        
        updateTableCourse();
    }
    private void updateTableCourse(){
        tableCourse = new JTable(tableModel);
        tableCourse.setVisible(true);
        tableCourse.setAutoCreateRowSorter(true);
        tableCourse.setBounds(0,0,800,1000);
        PaginationDataProvider<Course> dataProvider = createDataProvider(listTableCourse);
        PaginatedTableDecorator<Course> paginatedDecorator = PaginatedTableDecorator.decorate(tableCourse,
                dataProvider, new int[]{5, 10, 20, 50, 75, 100}, 10);
        jPaneTable= paginatedDecorator.getContentPanel();
        jPaneTable.setVisible(true);
        jPaneTable.setBounds(0,0,800,1000);
        
        this.jPanelTableCourse.setSize(800,1000);
        this.jPanelTableCourse.setPreferredSize(new Dimension(800,1000));
        this.jPanelTableCourse.add(jPaneTable);
        this.jPanelTableCourse.revalidate();
        this.jScrollPaneTableCourse.revalidate();
        this.revalidate();
        this.jPanelTableCourse.repaint();
        this.repaint();
    }
    private static TableModel createObjectDataModel() {
        return new ObjectTableModel<Course>() {
            @Override
            public Object getValueAt(Course course, int columnIndex) {
                switch (columnIndex) {
                    case 0:
                        return course.getCourseID();
                    case 1:
                        return course.getCourseName();
                    case 2:
                        return course.getCredit();
                    case 3:
                        return course.getCourseCondition();
                    case 4:
                        return course.getCourseType();
                    case 5:
                        return course.getProgramId();
                }
                return null;
            }

            @Override
            public int getColumnCount() {
                return 6;
            }
            @Override
            public String getColumnName(int column) {
                switch (column) {
                    case 0:
                        return "CourseID";
                    case 1:
                        return "CourseName";
                    case 2:
                        return "Credit";
                    case 3:
                        return "CourseCondition";
                    case 4:
                        return "CourseType";
                    case 5:
                        return "ProgramId";
                }
                return null;
            }
        };
    }
    private PaginationDataProvider<Course> createDataProvider(List<Course> listTableCourse) {
        return new PaginationDataProvider<Course>() {
            @Override
            public int getTotalRowCount() {
                return listTableCourse.size();
            }

            @Override
            public List<Course> getRows(int startIndex, int endIndex) {
                return listTableCourse.subList(startIndex, endIndex);
            }
        };
    }
         
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddCourse;
    private javax.swing.JButton jButtonDeleteClass;
    private javax.swing.JButton jButtonEditCourse;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonShowAllCourse;
    private javax.swing.JLabel jLabelCourseId;
    private javax.swing.JLabel jLabelCourseName;
    private javax.swing.JLabel jLabelSearch;
    private javax.swing.JPanel jPanelTableCourse;
    private javax.swing.JScrollPane jScrollPaneTableCourse;
    private javax.swing.JTextField jTextFieldCourseId;
    private javax.swing.JTextField jTextFieldCourseName;
    // End of variables declaration//GEN-END:variables
}
