/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin.View;

import Course.View.ManagementCourseForm;
import java.awt.Dimension;
import javax.swing.JPanel;
import javax.swing.WindowConstants;

/**
 *
 * @author haidt
 */
public class AdminMainPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminMainPafe
     */
    public AdminMainPage() {
        initComponents();
        setComponentSize();
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }
    public void setComponentSize(){
        this.setResizable(false);
        this.setBounds(0, 0,1300,700);
        jPanelHeader.setBounds(0, 0,300,700);
        jPanelContent.setBounds(0, 0,800,700);
        jPanelMenu.setBounds(0,0,300,700);
        jPanelHeader.setPreferredSize(new Dimension(300,700));
        jPanelContent.setPreferredSize(new Dimension(1000,700));
        jPanelMenu.setPreferredSize(new Dimension(300,700));
        jPanelContent.repaint();
        jPanelHeader.repaint();
    }
    public void initialization(){
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContent = new javax.swing.JPanel();
        jPanelHeader = new javax.swing.JPanel();
        jLabelNameHeader = new javax.swing.JLabel();
        jPanelMenu = new javax.swing.JPanel();
        jButtonManageCourse = new javax.swing.JButton();
        jButtonManageClass = new javax.swing.JButton();
        jButtonManagePermision = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 153));

        jPanelContent.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanelContentLayout = new javax.swing.GroupLayout(jPanelContent);
        jPanelContent.setLayout(jPanelContentLayout);
        jPanelContentLayout.setHorizontalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );
        jPanelContentLayout.setVerticalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
        );

        jPanelHeader.setBackground(new java.awt.Color(0, 0, 153));

        jLabelNameHeader.setBackground(new java.awt.Color(0, 0, 153));
        jLabelNameHeader.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabelNameHeader.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNameHeader.setText("Admin Main Page");

        jPanelMenu.setBackground(new java.awt.Color(0, 0, 204));

        jButtonManageCourse.setBackground(new java.awt.Color(0, 51, 204));
        jButtonManageCourse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonManageCourse.setForeground(new java.awt.Color(255, 255, 255));
        jButtonManageCourse.setText("Quản lý học phần");
        jButtonManageCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonManageCourseMouseClicked(evt);
            }
        });
        jButtonManageCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageCourseActionPerformed(evt);
            }
        });

        jButtonManageClass.setBackground(new java.awt.Color(51, 0, 204));
        jButtonManageClass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonManageClass.setForeground(new java.awt.Color(255, 255, 255));
        jButtonManageClass.setText("Quản lý lớp học");
        jButtonManageClass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonManageClassMouseClicked(evt);
            }
        });

        jButtonManagePermision.setBackground(new java.awt.Color(51, 0, 204));
        jButtonManagePermision.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonManagePermision.setForeground(new java.awt.Color(255, 255, 255));
        jButtonManagePermision.setText("Quản lý lớp học");
        jButtonManagePermision.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonManagePermisionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonManageClass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonManageCourse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(jButtonManagePermision, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButtonManageCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jButtonManageClass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonManagePermision, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelNameHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabelNameHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(532, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(230, Short.MAX_VALUE)
                    .addComponent(jPanelContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonManageCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonManageCourseActionPerformed

    private void jButtonManageCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonManageCourseMouseClicked
        // TODO add your handling code here:
        ManagementCourseForm managementCourseForm= new ManagementCourseForm(this);
        managementCourseForm.setBounds(50,0,1000,700);
        managementCourseForm.setPreferredSize(new Dimension(1000,700));
        managementCourseForm.setVisible(true);
        jPanelContent.add(managementCourseForm);
        jPanelContent.revalidate();
        jPanelHeader.revalidate();
        jPanelContent.repaint();
        jPanelHeader.repaint();
    }//GEN-LAST:event_jButtonManageCourseMouseClicked

    private void jButtonManageClassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonManageClassMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonManageClassMouseClicked

    private void jButtonManagePermisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonManagePermisionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonManagePermisionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdminMainPage adminMainPage=new AdminMainPage();
                adminMainPage.setVisible(true);
            }
        });
    }
    public JPanel getPanelContent(){
        return this.jPanelContent;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonManageClass;
    private javax.swing.JButton jButtonManageCourse;
    private javax.swing.JButton jButtonManagePermision;
    private javax.swing.JLabel jLabelNameHeader;
    public javax.swing.JPanel jPanelContent;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelMenu;
    // End of variables declaration//GEN-END:variables
}
